version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./proyecto:/app:delegated
    environment:
      - NODE_ENV=development
